{% set python_min = "3.11" %}
{% set name = "xbitinfo-outputs" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/observingClouds/xbitinfo/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5f0966bb037d3fff5566833f92fd3190c3e52aba003799919755d340740860ab

build:
  number: 0
  noarch: python

test:
  requires:
    - pooch
    - netcdf4
    - python {{ python_min }}

outputs:
  - name: xbitinfo-python
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - pdm-backend
      run:
        - python >={{ python_min }},<3.14
        - cmcrameri
        - dask-core
        - matplotlib-base >=3.9.0
        - numcodecs >=0.10.0
        - prefect >=3.3.0
        - tqdm
        - xarray
        # io
        - netcdf4
        - zarr
        
      
    test:
      imports:
        - xbitinfo
      commands:
        - pip check
      requires:
        - pip

  - name: xbitinfo
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('xbitinfo-python', max_pin="x.x.x") }}
        - pyjulia >=0.5.7
        - julia >=1.6.0,<1.8.0

about:
  home: https://github.com/observingClouds/xbitinfo
  summary: Retrieve information content and compress accordingly.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rsignell-usgs
    - observingClouds
    - ocefpaf
