{% set name = "xbitinfo" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xbitinfo-{{ version }}.tar.gz
  sha256: 31024abfbf0e6853531dc6315a250ef2e4509a6d846cc44ddff5c80f12a58ae9
  patches:
    - install_julia.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=30.3.0
    - setuptools-scm
    - setuptools_scm_git_archive
    - pyjulia >=0.5.7
    - julia >=1.6.0,<1.8.0
  run:
    - python >=3.8
    - xarray
    - pyjulia >=0.5.7
    - julia >=1.6.0,<1.8.0
    - tqdm
    - numcodecs >=0.10.0
    # extras::viz
    - matplotlib-base
    - cmcrameri
    # extras::prefect
    - prefect >=1.0.0

test:
  imports:
    - xbitinfo
  commands:
    - pip check
  requires:
    - pip
    - pooch
    - netcdf4

about:
  home: https://github.com/observingClouds/xbitinfo
  summary: Retrieve information content and compress accordingly.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rsignell-usgs
    - observingClouds
    - ocefpaf
