{% set name = "xbitinfo-outputs" %}
{% set version = "0.0.4.dev1" %}
{% set commit = "c917b4304e26a8cc69a9eabd2cc128287f8e7cd4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/observingClouds/xbitinfo/archive/{{ commit }}.tar.gz
  sha256: aaf152bd9b7a0472f688799b36699225ed093509f3b5afccefc871b62f02eb3b

build:
  number: 2
  noarch: python

test:
  requires:
    - pooch
    - netcdf4
    - python {{ python_min }}

outputs:
  - name: xbitinfo-python
    build:
      noarch: python
    script: build_base.sh
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools >=30.3.0
        - setuptools-scm
      run:
        - python >={{ python_min }}
        - xarray
        - tqdm
        - numcodecs >=0.10.0
        # extras::viz
        - matplotlib-base
        - cmcrameri
        # extras::prefect
        - prefect >=1.0.0,<2.0
        # io
        - netcdf4
        - zarr
    test:
      imports:
        - xbitinfo
      # commands:
        # remove pip-check b/c this old version of prefect has bad metadata.
        # WARNING: Error parsing dependencies of prefect: Expected matching RIGHT_PARENTHESIS for LEFT_PARENTHESIS, after version specifier
        # kubernetes (>=9.0.0a1.0) ; extra == 'all_extras'
        # - pip check
      requires:
        - pip

  - name: xbitinfo
    build:
      noarch: generic
    requirements:
      run:
        - {{ pin_subpackage('xbitinfo-python', max_pin="x.x.x") }}
        - pyjulia >=0.5.7
        - julia >=1.6.0,<1.8.0

about:
  home: https://github.com/observingClouds/xbitinfo
  summary: Retrieve information content and compress accordingly.
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - rsignell-usgs
    - observingClouds
    - ocefpaf
